export const LOAD_SYSTEM = 'LOAD_SYSTEM'

export const Test = {
    START_TEST: 'TEST/START_TEST',
    END_TEST: 'TEST/STOP_TEST',
    CREATE_NEW_PROGRAM: 'TEST/CREATE_PROGRAM',
    RENAME_PROGRAM: 'TEST/RENAME',
    ADD_STEP: 'TEST/ADD_STEP'
}

export const Protocols = {
    START_LOADING: 'PROTOCOLS/START_LOADING',
    STOP_LOADING: 'PROTOCOLS/STOP_LOADING',
    SET_BEGIN_DATA: 'PROTOCOLS/SET_BEGIN_DATA',
    SET_END_DATA: 'PROTOCOLS/SET_END_DATA',
    SET_PROGRAM_NAME: 'PROTOCOLS/SET_PROGRAM_NAME',
    FILTER_DATA: 'PROTOCOLS/FILTER'
}

export const Accidents = {
    START_LOADING: 'ACCIDENTS/START_LOADING',
    STOP_LOADING: 'ACCIDENTS/STOP_LOADING'
}

export const Employees = {
    START_LOADING: 'EMPLOYEES/START_LOADING',
    STOP_LOADING: 'EMPLOYEES/STOP_LOADING'
}

export const EditProtocols = {
    START_LOADING: 'PROTOCOLS/START_LOADING',
    STOP_LOADING: 'PROTOCOLS/STOP_LOADING',
    EDIT_PROTOCOL: 'PROTOCOLS/EDIT',
    CANCEL_CHANGES: 'PROTOCOLS/CANCEL',
    SAVE_CHANGES: 'PROTOCOLS/SAVE',
    ADD: 'PROTOCOLS/ADD',
    DELETE: 'PROTOCOLS/DELETE'
}

export const EditMethodologys = {
    START_LOADING: 'METHODOLOGYS/START_LOADING',
    STOP_LOADING: 'METHODOLOGYS/STOP_LOADING',
    EDIT_METHODOLOGY: 'METHODOLOGYS/EDIT',
    CANCEL_CHANGES: 'METHODOLOGYS/CANCEL',
    SAVE_CHANGES: 'METHODOLOGYS/SAVE',
    ADD: 'METHODOLOGY/ADD',
    DELETE: 'METHODOLOGY/DELETE'
}